# Define target output
target: pdi

# Define Firmware Version: v1.0.0.0
export PRJ_VERSION = 0x01000000

# Define target part
export PRJ_PART = xcvc1902-vsva2197-2MP-e-S

# Define the TOP directory
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
